### PR TITLE
🍰 Make hashtag links URL safe

### LINKED ISSUE #1276: 🐛 [Bug] Hashtag links are not URL safe
## :bug: Bugreport
Some of the imported hashtags contain whitespaces. If you click on one of them, you get to page `/search/hashtag/#%20Appeninnen` and redirected to the index page, thus not filtering for any hashtags.

### Steps to reproduce the behavior
1. Write a post with a hashtag, choose an existing one with a whitespace
2. Save the post
3. Click on the hashtag
4. Get redirected to the index page with the list of all posts unfiltered

2019-08-15-223129_1920x1080_scrot

### Expected behavior
You should see a list of posts that all have been tagged with the hashtag.

### Additional context

There are two things to be fixed here:
1. The database import should make use of [apoc.text.snakeCase()](https://neo4j-contrib.github.io/neo4j-apoc-procedures/3.5/utilities/text-functions/#_convert_a_string_to_snake_case_with_literal_snakecase_literal) (this will be solved here #1399 )
2. The unnecessary redirect should be removed. Instead, the link to the hashtag search should have *safely encode* the filter object as url params. This is an example of the string `# Appeninen` safely encoded: `http://localhost:3000/?hashtag=#%20Appenninen`

### PR DESCRIPTION
**Pull request by Tirokk**
## 🍰 Pullrequest

Make hashtag links URL safe.
Have the routing of a hashtag link direct.

### Issues

- fixes #1276

### Todo

- [x] direct routing of hashtag link

### CODE REVIEW

File: webapp/middleware/searchHashtag.js [hunk 1]
```diff
@@ -0,0 +1,16 @@
+import { exec, build } from 'xregexp/xregexp-all.js'
+
+export default async ({ store, env, route, redirect }) => {
+  let publicPages = env.publicPages
+  // only affect non public pages
```
Comment (mattwr18) [inline webapp/middleware/searchHashtag.js]: sorry, what does this mean? 
by `publicPages` do you mean pages that a user can visit without being signed in?
or is there some meaning for this I don't know about?

File: backend/src/middleware/hashtags/hashtagsMiddleware.spec.js [hunk 2]
```diff
@@ -129,8 +129,8 @@ describe('hashtags', () => {
         )
       })
 
-      describe('afterwards update the Post by removing a Hashtag, leaving a Hashtag and add a Hashtag', () => {
-        // The already existing Hashtag has no class at this point.
+      describe('afterwards update the Post by removing a hashtag, leaving a hashtag and add a hashtag', () => {
```
[the remark this answers is not in the document]
Comment (Tirokk) [reply backend/src/middleware/hashtags/hashtagsMiddleware.spec.js]: I my self had to read it twice, but than understand.
I should have corrected this at that moment, but somehow got over it. @mattwr18 

There is already a post generated with #Democracy and #Liberty hashtags.
By updating the post with #Elections and #Liberty only this both should be related to the post. So the statement was one (#Democracy) is removed, one is left (#Liberty) and one is new (#Elections). Much to complicated …
But a statement like `only the both hashtags in the updated content are related` will be clear and much more understandable.

File: webapp/middleware/searchHashtag.js (hunk 1 above)
Comment (Tirokk) [reply webapp/middleware/searchHashtag.js]: This I have taken over from `webapp/middleware/authenticated.js`. @mattwr18 
In my understanding `publicPages ` do mean pages that a user can visit without being signed in. Yes.

File: backend/src/middleware/hashtags/hashtagsMiddleware.spec.js (hunk 2 above)
Comment (roschaefer) [inline backend/src/middleware/hashtags/hashtagsMiddleware.spec.js]:
```suggestion
      describe('updates the Post by removing, keeping and adding one hashtag respectively', () => {
```

File: webapp/components/Editor/nodes/Hashtag.js [hunk 3]
```diff
@@ -25,7 +25,7 @@ export default class Hashtag extends TipTapMention {
           'a',
           {
             class: this.options.mentionClass,
-            href: `/search/hashtag/${node.attrs.id}`,
+            href: `/search/hashtag/${encodeURI(node.attrs.id)}`,
```
Comment (roschaefer) [inline webapp/components/Editor/nodes/Hashtag.js]: Can't we use query parameters? :cry: 

I found out how to use [URL](https://nodejs.org/api/url.html) to encode/decode url params for relative URLs: Just use a dummy domain!

Example:

```js
const url = new URL('http://example.org')
url.searchParams.append('hashtag', 'ä  #')
url.search // returns ?hashtag=%C3%A4++%23
```

File: webapp/middleware/searchHashtag.js (hunk 1 above)
Comment (roschaefer) [reply webapp/middleware/searchHashtag.js]: You don't have to check public pages again. The `authenticated` middleware is one of two default middlewares checked for every route, as specified in [nuxt.config.js](https://github.com/Human-Connection/Human-Connection/blob/master/webapp/nuxt.config.js#L126).

I would not use a middleware for sth. that affects only one route, though!

File: webapp/middleware/searchHashtag.js [hunk 4]
```diff
@@ -0,0 +1,16 @@
...
+  if (publicPages.indexOf(route.name) >= 0) {
+    return true
+  }
+
+  const regX = build('^/search/hashtag/((\\pL+[\\pL0-9]*)|([0-9]+\\pL+[\\pL0-9]*))$')
+  const matchHashtag = route.fullPath ? exec(decodeURI(route.fullPath), regX) : null
+
+  if (!matchHashtag) return true
+
+  return redirect(`/?hashtag=${encodeURI(matchHashtag[1])}`)
```
Comment (roschaefer) [inline webapp/middleware/searchHashtag.js]: Something like this URL could be in the `href` above! :point_up:

File: webapp/nuxt.config.js [hunk 5]
```diff
@@ -123,7 +123,7 @@ export default {
   ],
 
   router: {
-    middleware: ['authenticated', 'termsAndConditions'],
+    middleware: ['authenticated', 'termsAndConditions', 'searchHashtag'],
```
Comment (roschaefer) [inline webapp/nuxt.config.js]:
```suggestion
    middleware: ['authenticated', 'termsAndConditions'],
```

You are adding a middleware for every route here. I would say the feature does not justify the added complexity :neutral_face:

File: webapp/pages/index.vue [hunk 6]
```diff
@@ -75,7 +75,10 @@ export default {
     MasonryGridItem,
   },
   data() {
-    const { hashtag = null } = this.$route.query
+    let { hashtag = null } = this.$route.query
+    if (hashtag) {
+      hashtag = decodeURI(hashtag)
```
Comment (roschaefer) [inline webapp/pages/index.vue]: Weird, the hashtag is not automatically decoded? :confused:

Comment (Tirokk) [reply webapp/pages/index.vue]: May I add to much `decodeURI` …

File: backend/src/middleware/hashtags/extractHashtags.js [hunk 7]
```diff
@@ -6,21 +6,21 @@ import { exec, build } from 'xregexp/xregexp-all.js'
...
-const regX = build('^/search/hashtag/((\\pL+[\\pL0-9]*)|([0-9]+\\pL+[\\pL0-9]*))$')
+const regX = build('^((\\pL+[\\pL0-9]*)|([0-9]+\\pL+[\\pL0-9]*))$')
 
 export default function(content) {
   if (!content) return []
   const $ = cheerio.load(content)
   // We can not search for class '.hashtag', because the classes are removed at the 'xss' middleware.
   //   But we have to know, which Hashtags are removed from the content as well, so we search for the 'a' html-tag.
-  const urls = $('a')
+  const ids = $('a[data-hashtag-id]')
```
Comment (mattwr18) [inline backend/src/middleware/hashtags/extractHashtags.js]: I like this change!

File: backend/src/middleware/hashtags/extractHashtags.spec.js [hunk 8]
```diff
@@ -8,9 +8,24 @@ describe('extractHashtags', () => {
...
-    it('finds links with and without ".hashtag" class and extracts Hashtag names', () => {
-      const content =
-        '<p><a class="hashtag" href="/search/hashtag/Elections">#Elections</a><a href="/search/hashtag/Democracy">#Democracy</a></p>'
+    it('not `class="hashtag"` but `data-hashtag-id="something"` makes a link a hashtag link', () => {
+      const content = `
+        <p>
+          <a
+            class="hashtag"
+            data-hashtag-id="Elections"
+            href="/?hashtag=Elections"
```
Comment (Tirokk) [inline backend/src/middleware/hashtags/extractHashtags.spec.js]: What I don’t like at this link query in general: It doesn’t say anything about this query is to be searched for.

File: webapp/components/Editor/nodes/Hashtag.js [hunk 9]
```diff
@@ -21,11 +21,15 @@ export default class Hashtag extends TipTapMention {
     return {
       ...super.schema,
       toDOM: node => {
+        // use a dummy domain because URL cannot handle relative urls
+        const url = new URL('/', 'http://example.org')
```
Comment (mattwr18) [inline webapp/components/Editor/nodes/Hashtag.js]: shouldn't we just use something else that can handle it then?

Comment (mattwr18) [reply webapp/components/Editor/nodes/Hashtag.js]: actually, looking at the docs, and what you are actually doing here, if the only thing you are using is `url.search` then you could just use our domain instead of a dummy one

File: backend/src/middleware/hashtags/extractHashtags.spec.js [hunk 10]
```diff
@@ -8,9 +8,24 @@ describe('extractHashtags', () => {
   })
 
   describe('searches through links', () => {
-    it('finds links with and without ".hashtag" class and extracts Hashtag names', () => {
-      const content =
-        '<p><a class="hashtag" href="/search/hashtag/Elections">#Elections</a><a href="/search/hashtag/Democracy">#Democracy</a></p>'
+    it('not `class="hashtag"` but `data-hashtag-id="something"` makes a link a hashtag link', () => {
```
Comment (Tirokk) [inline backend/src/middleware/hashtags/extractHashtags.spec.js]: This sounds nice, but is not true in real.
Because the `data-hashtag-id` is deleted by saving the content in the database.
On reedit it is no link anymore in this sense.

File: backend/src/middleware/hashtags/hashtagsMiddleware.spec.js [hunk 11]
```diff
@@ -129,10 +148,29 @@ describe('hashtags', () => {
         )
       })
 
-      describe('afterwards update the Post by removing a Hashtag, leaving a Hashtag and add a Hashtag', () => {
-        // The already existing Hashtag has no class at this point.
-        const postContent =
-          '<p>Hey Dude, <a class="hashtag" href="/search/hashtag/Elections">#Elections</a> should work equal for everybody!? That seems to be the only way to have equal <a href="/search/hashtag/Liberty">#Liberty</a> for everyone.</p>'
+      describe('updates the Post by removing, keeping and adding one hashtag respectively', () => {
```
Comment (Tirokk) [inline backend/src/middleware/hashtags/hashtagsMiddleware.spec.js]: This is a false successful test !!! 🤔
Because the `data-hashtag-id` is deleted by saving the content in the database.
On reedit it is no link anymore.
Therefore here you create a test that’s not existent in reality.
That’s why we used the `href` to search for a hashtag.

File: webapp/components/Editor/nodes/Hashtag.js (hunk 9 above)
Comment (Tirokk) [reply webapp/components/Editor/nodes/Hashtag.js]: Yes @mattwr18 , I would like to see our domain here as well! 😘

File: backend/src/middleware/hashtags/extractHashtags.js (hunk 7 above)
Comment (Tirokk) [reply backend/src/middleware/hashtags/extractHashtags.js]: @mattwr18 This change breaks the functionality. 😂

File: webapp/components/Editor/nodes/Hashtag.js (hunk 9 above)
Comment (Tirokk) [reply webapp/components/Editor/nodes/Hashtag.js]: What will be the network domain at the end?
`https://human-connection.org` is used for the donation and information page at the moment.
But I decided to change it to this. Hope it is okay for you @roschaefer !?

**Comment by Tirokk** [comment]
I correct myself: The a-tag property `data-hashtag-id` gets stored in the database:

Bildschirmfoto 2019-09-17 um 10 28 52

… but does not make it into the editor again:

Bildschirmfoto 2019-09-17 um 10 31 45

**Comment by roschaefer** [comment]
@Tirokk thank you for the review! This is a nasty bug with tiptap and re-rendering/parsing existing content.

2019-09-17-110850_1920x1080_scrot

The `data-hashtag-id` should be there now.

**Comment by Tirokk** [comment]
This works now for me @roschaefer .
So I formal approve our PR !!! And you can merge.
PS: … if you get the build passing. Which seems unrelated …
