### PR TITLE
Fix #822 by updating the counts of the user

### LINKED ISSUE #822: 🐛 [Bug] load more is sometimes wrong on User Profile in the three Tabs
## :bug: Bugreport

At the Users Profile sometimes the `load more` is shown, even when there is nothing to load!

### Steps to reproduce the behavior
1. login as Jenny Rostock
2. go to Users Profile
3. delete a Post of yourself
4. switch between Tabs
5. suddenly the `load more` showed up at the Posts and Comments Tab

Bildschirmfoto 2019-06-13 um 18 28 46

Bildschirmfoto 2019-06-13 um 18 28 36

### PR DESCRIPTION
**Pull request by roschaefer**
The load more button depends on the total of the posts available.
Removing posts changes the total counts, so we have to manually update
it.

### Issues

- fixes #822 

### Todo

- [X] None

### CODE REVIEW

File: webapp/pages/profile/_id/_slug.vue [hunk 1]
```diff
@@ -331,6 +331,10 @@ export default {
     },
   },
   methods: {
+    removePostFromList(index) {
+      this.activePosts.splice(index, 1)
```
Comment (Tirokk) [inline webapp/pages/profile/_id/_slug.vue]: From where you get the `index` parameter, dear? @roschaefer 
After you deleted it from the `for loop` above …

Comment (roschaefer) [reply webapp/pages/profile/_id/_slug.vue]: The index parameter is still there! You pass the function `removePostFromList` and it has the signature of expecting one argument. When it's called it gets called with the required index param.

Comment (roschaefer) [reply webapp/pages/profile/_id/_slug.vue]: get called with the right arguments
