### PR TITLE
Add LegacyEmbeds component to fix bug

### LINKED ISSUE #2259: 🐛 [Bug] Embeds are not displayed
## :bug: Bugreport

Probably after #2242 the previous embeds are not displayed anymore. See:

Screenshot - 2019-11-16T185240 630

### Steps to reproduce the behavior

It's difficult to reproduce since you need old production data. But the above post is here: https://human-connection.social/post/fc2dd986-c8fb-4251-a653-63541a844b66/meine-erste-vorlesung-an-der-htw-berlin-hochschule-fur-technik-und-wirtschaft

### Expected behavior

The editor should parse the old embeds just fine.

### Additional context

https://human-connection.social/post/43fb27ec-fa26-4c42-88ed-179542796358/human-connection-5#commentId-c6440f59-e266-4888-9e96-6831ac249c13

### PR DESCRIPTION
**Pull request by mattwr18**
### Issues

- fixes #2259

### CODE REVIEW

File: webapp/components/Editor/nodes/LegacyEmbed.js [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+        {
+          href: node.attrs.dataEmbedUrl,
+          class: 'embed',
+          target: '_blank',
+        },
+      ],
+    }
+  }
+
+  get view() {
```
Comment (roschaefer) [inline webapp/components/Editor/nodes/LegacyEmbed.js]: Could you import that method from the other node?

File: webapp/components/Editor/defaultExtensions.js [hunk 2]
```diff
@@ -44,5 +45,13 @@ export default function defaultExtensions(component) {
         return embed
       },
     }),
+    new LegacyEmbed({
+      onEmbed: async ({ url }) => {
```
Comment (roschaefer) [inline webapp/components/Editor/defaultExtensions.js]: Save a `const onEmbed = async ({url}) => { /* ... */ }` and reuse that.
