### PR TITLE
Fix: Email is Case-Sensitive

### LINKED ISSUE #2057: 🐛 [Bug] Password-Reset/Registration Dialogue is Case-Sensitive
## :bug: Bugreport
When users want to reset their passwords or want to register and they use emails with uppcercase in it, these can not be found and you get an email which says:  _You requested a password reset but unfortunately we couldn't find an account associated with your e-mail address. Did you maybe use another one when you signed up?_

wrong-email

### Steps to reproduce the behavior
1. Open reset Password dialogue
2. Type in your emial with upper case letters

Screenshot - 2019-10-29T171429 064

Screenshot - 2019-10-29T171929 698

### Expected behavior
The given email for reset should be converted to lowercase

### Version & Environment
any

### PR DESCRIPTION
**Pull request by roschaefer**
## 🍰 Pullrequest
This was much more difficult than expected because of all those places where we use emails.

### Issues

- fix #2057

### Todo

- [x] Use backend server response for submit messages (it's kind of done, one of the graphql mutation is not responding with the created object)

### CODE REVIEW

File: webapp/components/PasswordReset/Request.vue [hunk 1]
```diff
@@ -68,8 +69,11 @@ export default {
     }
   },
   computed: {
+    email() {
+      return normalizeEmail(this.formData.email)
+    },
     submitMessage() {
-      const { email } = this.formData
+      const { email } = this
```
Comment (roschaefer) [inline webapp/components/PasswordReset/Request.vue]: I think this is the graphql mutation which has Boolean as return type. Thus we cannot take the normalized email from the backend but have to normalize it client-wise.
