### PR TITLE
Paginate moderations page without losing filtering

### LINKED ISSUE #2442: 🐛 [Bug] reports query is too expensive and times out often
## :bug: Bugreport

The reports query fetches all reports, which have nested `FiledReports`, nested `reviews`,  nested `resources`, which have nested attributes as well. 
This makes it an extremely expensive request. Leading to time outs.

### Steps to reproduce the behavior
1. log in as admin
2. go to `/moderation`
3. see if the reports load
4. ...
5. Profit

### Expected behavior

We'd expect that `reports` would be shown

### Additional context

@roschaefer suggested we could do `eager` loading of certain resources.
We could also try pagination

### PR DESCRIPTION
**Pull request by mattwr18**
Co-authored-by: Tirokk <wolle.huss@pjannto.com>

### Issues

- fixes #2442

### CODE REVIEW

File: webapp/graphql/Moderation.js [hunk 1]
```diff
@@ -82,9 +82,6 @@ export const reportsListQuery = () => {
             name
             disabled
             deleted
-            followedByCount
-            contributionsCount
-            commentedCount
```
Comment (roschaefer) [inline webapp/graphql/Moderation.js]: Awww yeah. That's what I wanted to do in my next PR. I'm going to rebase my code on that.

File: webapp/components/User/User.vue [hunk 2]
```diff
@@ -26,7 +26,7 @@
         </div>
       </nuxt-link>
     </template>
-    <template slot="popover">
+    <template slot="popover" v-if="showCounts">
```
Comment (roschaefer) [inline webapp/components/User/User.vue]: I would say `showPopover` no?

Comment (mattwr18) [reply webapp/components/User/User.vue]: yes, that's better
