### PR TITLE
Authorisation problem when disabling a post

### LINKED ISSUE #734: 🐛 [Bug] Authorization problem when disabling a post.
## :bug: Bugreport
Authorization problem when locking a post. 

Moderators and admins can do the blocking of a post. as admin I get a GraphQL hint when blocking a post that there is an authorization problem. but the process in the background is running clean. 

### Steps to reproduce the behavior
1. login as moderator and disable a post
2. login as admin and disable a post
3. toast error message 

Bildschirmfoto vom 2019-06-04 09-01-05

### PR DESCRIPTION
**Pull request by Tirokk**
## 🍰 Pullrequest

There was an GraphQL error message, if the User (Moderator or Admin) disables a Post of somebody. See issue #734 .

- It is caused by the call of `deletePostCallback`, which should not happen here, because of a bug in the callback concept.

Therefore refinement and refactoring of Modal callbacks is necessary.

### Issues

- fixes #734

### CODE REVIEW

**Comment by Tirokk** [comment]
Got nice help and influences of @mattwr18 !!!

File: webapp/pages/profile/_id/_slug.vue [hunk 1]
```diff
@@ -266,6 +267,35 @@ export default {
       voted: false,
       page: 1,
       pageSize: 6,
+      modalsData: {
+        delete: {
+          titel: () => {
```
Comment (roschaefer) [inline webapp/pages/profile/_id/_slug.vue]:
```suggestion
          title: () => {
```

File: webapp/pages/profile/_id/_slug.vue [hunk 2]
```diff
@@ -266,6 +267,35 @@ export default {
       voted: false,
       page: 1,
       pageSize: 6,
+      modalsData: {
+        delete: {
```
Comment (roschaefer) [inline webapp/pages/profile/_id/_slug.vue]: If find this slightly inconsistently named - down below it's called `disableCallback` and `reportCallback` and here it's just `delete`.

**Comment by mattwr18** [comment]
I think @Tirokk just pushed this up because he needed to go

we had a pairing session together where we talked about the direction of the modals, which was recorded, if you are interested in seeing @roschaefer. 

Then, this was just to say that the process has started, but far from ready for a review... not that your comments are not helpful, just to keep it in perspective. :smile_cat:

File: webapp/pages/profile/_id/_slug.vue (hunk 1 above)
Comment (Tirokk) [reply webapp/pages/profile/_id/_slug.vue]: I have corrected this in my code …

**Comment by Tirokk** [comment]
Like @mattwr18 said. I use to push up my code, because I had to get off the work @roschaefer .
I am very happy for your suggestions and corrections. Therefore I made the beginning description more informativ. 😄💫

But I am not sure, if you should spend your time on work in progress, like this is marked as.
This work is at the beginning and just kind of in the middle of nowhere … 😘
This code is a first tryout which I created for and with @mattwr18 to see which structure would best fit. Nobody thought that this code would go anywhere …

Love you! 😍

IMG_1377

File: webapp/pages/profile/_id/_slug.vue (hunk 2 above)
Comment (Tirokk) [reply webapp/pages/profile/_id/_slug.vue]: This was related to my discussion for the right path with @mattwr18 and has nothing to do with real programming! @roschaefer

**Comment by Tirokk** [comment]
- Bug is fixed.
- Jest tests have to be reviewed by me and may be a little bit rewritten next week.

**Comment by Tirokk** [comment]
Still failing tests of two file which we have to rewrite.

Great to work with you on it @mattwr18 !!! 😍

File: webapp/components/ContentMenu.vue [hunk 3]
```diff
@@ -43,7 +43,13 @@ export default {
         return value.match(/(contribution|comment|organization|user)/)
       },
     },
-    callbacks: { type: Object, required: true },
+    modalsData: {
+      type: Object,
+      required: false,
+      // default: () => {
```
Comment (Kachulio1) [inline webapp/components/ContentMenu.vue]: We can remove the commented out code.

File: webapp/pages/post/_id/_slug/more-info.vue [hunk 4]
```diff
@@ -1,8 +1,6 @@
 <template>
   <ds-card>
-    <h2 style="margin-bottom: .2em;">
-      Mehr Informationen
-    </h2>
+    <h2 style="margin-bottom: .2em;">Mehr Informationen</h2>
```
Comment (mattwr18) [inline webapp/pages/post/_id/_slug/more-info.vue]: You probably don't want to make more changes to push up, but it would be nice to have this translated.. I guess there's another ticket to work through the untranslated texts, right?

File: webapp/pages/profile/_id/_slug.vue [hunk 5]
```diff
@@ -253,6 +252,7 @@ const tabToFilterMapping = ({ tab, id }) => {
 }
 
 export default {
+  name: 'HcUserProfile',
```
Comment (mattwr18) [inline webapp/pages/profile/_id/_slug.vue]: did we want to keep this change?

File: webapp/pages/profile/_id/_slug.vue [hunk 6]
```diff
@@ -365,6 +362,12 @@ export default {
         fetchPolicy: 'cache-and-network',
       })
     },
+    setActivePosts() {
+      if (!this.Post) {
+        return []
+      }
+      return this.uniq(this.Post.filter(post => !post.deleted))
+    },
```
Comment (mattwr18) [inline webapp/pages/profile/_id/_slug.vue]: could you explain what motivated these changes @Tirokk 
sorry, it's not obvious to me

File: webapp/pages/profile/_id/_slug.spec.js [hunk 7]
```diff
@@ -200,7 +162,10 @@ describe('ProfileSlug', () => {
           describe('pagination returned as many posts as available', () => {
             beforeEach(() => {
               const posts = [1, 2, 3, 4, 5, 6].map(id => {
-                return { ...aPost, id }
+                return {
+                  ...aPost,
+                  id,
+                }
```
[the remark this answers is not in the document]
Comment (Tirokk) [reply webapp/pages/profile/_id/_slug.spec.js]: It’s not my code. @mattwr18 
Probably @roschaefer wrote this. It should been overtaken from the master.

File: webapp/pages/profile/_id/_slug.vue (hunk 6 above)
Comment (Tirokk) [reply webapp/pages/profile/_id/_slug.vue]: This code is probably written by @roschaefer .

Here I rewrote it a little to get the delete Post on the User Profile working again. But nothing serious I think.
He filters the deleted Posts out of the list array I think.

File: webapp/components/utils/PostHelpers.js [hunk 8]
```diff
@@ -0,0 +1,43 @@
...
+          textIdent: 'delete.cancel',
+          callback: cancelCallback,
+        },
+      },
+    },
+  }
+}
+
+export function deletePostMutation(postId) {
+  // TODO: Replace "gqlMutation" with "DeletePost" from '~/graphql/PostMutations.js', has not worked for me.
```
[the remark this answers is not in the document]
Comment (Tirokk) [reply webapp/components/utils/PostHelpers.js]: I would love to try @mattwr18 .

File: webapp/pages/profile/_id/_slug.spec.js (hunk 7 above)
[the remark this answers is not in the document]
Comment (mattwr18) [reply webapp/pages/profile/_id/_slug.spec.js]: I was referring to the formatting of the code... which it's seems this `PR` introduced, but I don't think it's a big deal...

File: webapp/components/ContentMenu.vue (hunk 3 above)
Comment (Tirokk) [reply webapp/components/ContentMenu.vue]: This is not related to me. @Kachulio1

File: webapp/components/utils/PostHelpers.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (Tirokk) [reply webapp/components/utils/PostHelpers.js]: We have done. 💫 @mattwr18

File: webapp/pages/post/_id/_slug/more-info.vue (hunk 4 above)
Comment (Tirokk) [reply webapp/pages/post/_id/_slug/more-info.vue]: I have made a screenshot to my list … @mattwr18

File: webapp/pages/profile/_id/_slug.vue (hunk 5 above)
Comment (Tirokk) [reply webapp/pages/profile/_id/_slug.vue]: Yes
