### PR TITLE
Should fix #234 + refactor domain to hostname

### LINKED ISSUE #234: [AP] Search a user on mastodon gives 503 error
**Describe the bug**
We have the backend deployed which now should be able to return results for webfinger searches.

E.g. if I type in `https://nitro-staging.human-connection.org/api/.well-known/webfinger?resource=acct:bob-der-baumeister` into the URL I get:
```json
// 20190322110313
// https://nitro-staging.human-connection.org/api/.well-known/webfinger?resource=acct:bob-der-baumeister

{
  "subject": "acct:bob-der-baumeister@nitro-backend.human-connection",
  "links": [
    {
      "rel": "self",
      "type": "application/activity+json",
      "href": "https://nitro-backend.human-connection/users/bob-der-baumeister"
    }
  ]
}
```

However, if I search for this seeded user through Mastodon, I get a 503 HTTP error.

**To Reproduce**
1. Visit a mastodon instance
2. Click on "Search"
3. Type in `bob-der-baumeister@nitro-staging.human-connection.org/api/`
4. See 503 HTTP error

**Expected behavior**
I would expect to see the user "Bob der Baumeister" in the result set.

**Screenshots**
2019-03-22-110425_1920x1080_scrot

### PR DESCRIPTION
**Pull request by Mastercuber**
close #234

### CODE REVIEW

File: backend/src/activitypub/ActivityPub.js [hunk 1]
```diff
@@ -33,7 +33,9 @@ export default class ActivityPub {
     if (!activityPub) {
       dotenv.config()
       const url = new URL(process.env.GRAPHQL_URI)
-      activityPub = new ActivityPub(url.hostname || 'localhost', url.port || 4000, url.origin)
+      // TODO Check why the hostname attribute in the prod env not containing the tld! Following line is a quick fix!!
```
Comment (roschaefer) [inline backend/src/activitypub/ActivityPub.js]: @mastercuber I would like to fix this *the clean way:tm:*

**Comment by roschaefer** [comment]
@Mastercuber I updated the description. You can close issues via keywords on Github.

File: backend/src/activitypub/ActivityPub.js (hunk 1 above)
Comment (roschaefer) [reply backend/src/activitypub/ActivityPub.js]: https://nodejs.org/api/url.html#url_url_host this seems to be the clean fix.
