### PR TITLE
🍰 Add Cypher statement for ordering

### LINKED ISSUE #1924: 🐛 [Bug] Moderators reports list does not sort
## :bug: Bugreport

Moderators reports list does not sort.

Bildschirmfoto 2019-10-16 um 12 40 39

### Steps to reproduce the behavior
1. log in as moderator
2. in the users menu click on moderator
3. see the list

### Expected behavior

List should sort descent.

### PR DESCRIPTION
**Pull request by Tirokk**
#1314  🍰 Pullrequest

Add Cypher statement for ordering.

- minor db manipulation text change

### Issues

- fixes #1924

### Todo

- [X] None

### CODE REVIEW

File: backend/src/schema/resolvers/reports.js [hunk 1]
```diff
@@ -58,54 +59,68 @@ export default {
...
+      const { driver } = context
       const session = driver.session()
-      const res = await session.run(
-        `
+      let response
+      let orderByClause
+      switch (params.orderBy) {
+        // case 'createdAt_asc':
+        //   orderByClause = 'ORDER BY report.createdAt ASC'
+        //   break
```
Comment (mattwr18) [inline backend/src/schema/resolvers/reports.js]: I don't understand why this is commented out?
maybe because there is no UI to allow `moderators` to order how they want, but I am guessing.
If that is the case, I don't see the need to leave it commented out, since there is more than one UI... we have the playground, for example.

if there is no `orderBy` it just comes in whatever order the database happens to return it?

Comment (Tirokk) [reply backend/src/schema/resolvers/reports.js]: Okay. @mattwr18 
I was uncertain how to handle this.

> if there is no orderBy it just comes in whatever order the database happens to return it?

Yes! That was the cause I’ve seen that no ordering was applied.

**Comment by Tirokk** [comment]
That exactly happened to me (and you) 😅😂
