### PR TITLE
Limit suggestions list to 15, add component tests

### LINKED ISSUE #1396: Feature: Less hashtag suggestions in the editor menu
## :bug: Bugreport

Hashtags menu is has to many items.

Bildschirmfoto 2019-08-26 um 11 33 02

### Steps to reproduce the behavior
1. Create a post.
2. Use hashtag by typing `#`.
3. Look at menu length …

### Expected behavior

Menu with not more then 20-30 items!?

### PR DESCRIPTION
**Pull request by mattwr18**
### Issues

- fixes #1396

### CODE REVIEW

File: webapp/components/Editor/Editor.vue [hunk 1]
```diff
@@ -205,10 +205,13 @@ export default {
       if (!query) {
         return items
       }
-      return items.filter(item => {
+
+      items = this.suggestionType === HASHTAG ? this.hashtags : this.users
```
Comment (alina-beck) [inline webapp/components/Editor/Editor.vue]: I think I would rather pass all items (hashtags or users) to the new `Hashtag` or `Mention` instead of checking for the suggestion type again during the filtering process and then resetting items to the corresponding type.

We could still limit the number of displayed suggestions by returning `items.slice(0, 15)` when there is no query (in line `206`).

Seems a bit cleaner to me. What do you think?

File: webapp/components/Editor/Editor.vue [hunk 2]
```diff
@@ -205,10 +205,13 @@ export default {
...
+      const filteredList = items.filter(item => {
         const itemString = item.slug || item.id
         return itemString.toLowerCase().includes(query.toLowerCase())
       })
+      return filteredList.slice(0, 14)
```
Comment (alina-beck) [inline webapp/components/Editor/Editor.vue]: Is there a reason why you used `14` here and `15` above? I'd say let's maybe use the same number in both places? :smile:

File: webapp/components/Editor/Editor.spec.js [hunk 3]
```diff
@@ -98,6 +111,16 @@ describe('Editor.vue', () => {
         expect(wrapper.vm.editor.extensions.options.hashtag.items()).toEqual(propsData.hashtags)
       })
 
+      it('limits the suggestion list to 15 users', () => {
```
Comment (alina-beck) [inline webapp/components/Editor/Editor.spec.js]: copy pasta! 🍝 😆 should be `hashtags` instead of `users` here...

File: webapp/components/Editor/Editor.vue (hunk 1 above)
Comment (mattwr18) [reply webapp/components/Editor/Editor.vue]: yes, it does! I got it working, but then didn't take a step back to think about it critically... good catch!

File: webapp/components/Editor/Editor.vue (hunk 2 above)
Comment (mattwr18) [reply webapp/components/Editor/Editor.vue]: haha, just cause I originally had all as 14, but then forgot to change this one

File: webapp/components/Editor/Editor.spec.js (hunk 3 above)
Comment (mattwr18) [reply webapp/components/Editor/Editor.spec.js]: you caught me :open_mouth:
